#!/bin/sh
# Generate src/mxystdlib.c from std/*.mxy files
set -e

OUTFILE="src/mxystdlib.c"
STDDIR="std"

cat > "$OUTFILE" << 'HEADER'
/* AUTO-GENERATED by scripts/genstdlib.sh — do not edit */
#include <string.h>
#include "mxystdlib.h"

static const StdlibEntry stdlib_entries[] = {
HEADER

count=0
for f in "$STDDIR"/*.mxy; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    path="std/$name"

    printf '    { "%s",\n' "$path" >> "$OUTFILE"

    # Convert file contents to C string literals line by line
    while IFS= read -r line || [ -n "$line" ]; do
        # Escape backslashes, then double quotes
        escaped=$(printf '%s' "$line" | sed 's/\\/\\\\/g; s/"/\\"/g')
        printf '      "%s\\n"\n' "$escaped" >> "$OUTFILE"
    done < "$f"

    printf '    },\n' >> "$OUTFILE"
    count=$((count + 1))
done

cat >> "$OUTFILE" << FOOTER
};

static const int stdlib_count = $count;

const char *stdlib_lookup(const char *path) {
    for (int i = 0; i < stdlib_count; i++)
        if (strcmp(stdlib_entries[i].path, path) == 0)
            return stdlib_entries[i].source;
    return NULL;
}
FOOTER

echo "Generated $OUTFILE with $count modules"
